import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
         int i;
        Scanner sc = new Scanner(System.in);
        int number = sc.nextInt();
        if (number==5) {
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }

        } else if (number==6) {
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
            number--;
            System.out.println(" ");
            for (i = 1; i <= number; i++) {
                System.out.print(i);
                System.out.print(" ");
            }
        }
        /* Enter your code here. Read input from STDIN. Print output to STDOUT. Your class should be named Solution. */
    }
}